version: "3.11.4"

services:

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=TaskApp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  web:
    build: ./TaskApp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./TaskApp/:/usr/src/TaskApp/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
    