# Generated by Django 5.0.1 on 2024-01-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='executing_user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='executing_user',
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='executing_user_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='executing_user_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
