# Generated by Django 5.0.1 on 2024-01-20 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_historicaltask_executing_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='executing_user_username',
        ),
        migrations.RemoveField(
            model_name='task',
            name='executing_user_username',
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='executing_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='executing_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
